<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTCH-5CD105HTG9" name="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion" tests="28" failures="4" timestamp="1 Apr 2021 15:56:10 GMT" time="858.887" errors="2">
  <testcase name="ItemSelectQuestion_DeleteAnOptionFromAnItemSelectQuestion_status204" time="36.298" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_MoveASelectQuestionFromItemOption_status400" time="27.466" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion">
    <error type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion.ItemSelectQuestion_MoveASelectQuestionFromItemOption_status400(Restassured_Automation_ItemSelectQuestion.java:1883)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	... 28 more
]]>
    </error>
  </testcase> <!-- ItemSelectQuestion_MoveASelectQuestionFromItemOption_status400 -->
  <testcase name="ItemSelectQuestion_CreateANewOptionGroupForAnItemSelectQuestionStatus_404" time="28.996" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_GetOptionsForASpecificItemSelectQuestionMethodologyItem_status200" time="28.235" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_UpdateASelectQuestionItemOptionGroup_400" time="36.182" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_CreateANewOptionGroupForAnItemSelectQuestionStatus_400" time="29.830" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PostCreateANewOptionForAnItemSelectQuestion_status400" time="24.494" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_MoveASelectQuestionFromItemOption_status404" time="0.435" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion">
    <error type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion.ItemSelectQuestion_MoveASelectQuestionFromItemOption_status404(Restassured_Automation_ItemSelectQuestion.java:1922)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
	... 28 more
]]>
    </error>
  </testcase> <!-- ItemSelectQuestion_MoveASelectQuestionFromItemOption_status404 -->
  <testcase name="ItemSelectQuestion_UpdateASelectQuestionItemOptionGroup_404" time="32.302" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion.ItemSelectQuestion_UpdateASelectQuestionItemOptionGroup_404(Restassured_Automation_ItemSelectQuestion.java:1362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ItemSelectQuestion_UpdateASelectQuestionItemOptionGroup_404 -->
  <testcase name="ItemSelectQuestion_PutSafelyInitializeNewOptionsForASelectQuestion_status404" time="23.906" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_CreateANewOptionGroupForAnItemSelectQuestionStatus_200" time="37.857" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_DeleteAnOptionGroupFromAnItemSelectQuestion_404" time="36.894" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PatchUpdateASelectQuestionItemOption_status400" time="25.939" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PutSafelyInitializeNewOptionsForASelectQuestion_status200" time="28.252" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_DeleteAnOptionFromAnItemSelectQuestion_status404" time="32.227" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PostCreateANewOptionForAnItemSelectQuestion_status404" time="24.433" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_EndToEnd_Scenario" time="40.542" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PatchUpdateASelectQuestionItemOption_status200" time="37.379" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PostCreateANewOptionForAnItemSelectQuestion_status200" time="27.810" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_DeleteAnOptionGroupFromAnItemSelectQuestion_400" time="44.678" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion">
    <failure type="java.lang.AssertionError" message="expected [400] but found [204]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [204]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion.ItemSelectQuestion_DeleteAnOptionGroupFromAnItemSelectQuestion_400(Restassured_Automation_ItemSelectQuestion.java:1740)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ItemSelectQuestion_DeleteAnOptionGroupFromAnItemSelectQuestion_400 -->
  <testcase name="ItemSelectQuestion_MoveASelectQuestionFromItemOption_status200" time="33.895" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion">
    <failure type="java.lang.AssertionError" message="expected [204] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion.ItemSelectQuestion_MoveASelectQuestionFromItemOption_status200(Restassured_Automation_ItemSelectQuestion.java:1818)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ItemSelectQuestion_MoveASelectQuestionFromItemOption_status200 -->
  <testcase name="ItemSelectQuestion_PatchUpdateASelectQuestionItemOption_status404" time="28.457" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_UpdateASelectQuestionItemOptionGroup_204" time="39.621" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_DeleteAnOptionGroupFromAnItemSelectQuestion_204" time="43.519" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_GetOptionsForASpecificItemSelectQuestionMethodologyItem_status404" time="24.567" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_PutSafelyInitializeNewOptionsForASelectQuestion_status400" time="23.772" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
  <testcase name="ItemSelectQuestion_DeleteAnOptionFromAnItemSelectQuestion_status400" time="29.048" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion.ItemSelectQuestion_DeleteAnOptionFromAnItemSelectQuestion_status400(Restassured_Automation_ItemSelectQuestion.java:1007)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ItemSelectQuestion_DeleteAnOptionFromAnItemSelectQuestion_status400 -->
  <testcase name="ItemSelectQuestion_GetOptionsForASpecificItemSelectQuestionMethodologyItem_status400" time="31.853" classname="restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion"/>
</testsuite> <!-- restassured.automation.testcases.Restassured_Automation_ItemSelectQuestion -->
